### PR TITLE
Test for "Get - nothing Request"

### PR DESCRIPTION
**Pull request by ohodovaniuk1**
Test for "GET - nothing request" now works

### CODE REVIEW

**Comment by ohodovaniuk1** [comment]
I have rewritten the tester code that has previously been commented out. Now test #4 successfully requests the following URL: "/api/phonenumbers/parse/text/nothing" and provides correct test response message "should return an empty array". The logic of the tester is still the same and the styling is virtually identical. The only thing that i changed is the syntax to make the tester run. Also i have noticed that the tester for pdf URL throws an error. Let me know if it also needs a fix.

**Comment by apetov** [comment]
Thank you, @ohodovaniuk1 ! 
Can you please elaborate on PDF test error? What kind of trouble you're having?

**Comment by apetov** [comment]
@ohodovaniuk1 , ignore my previous message. I fixed the problem. 
In order to get the test for PDF working, you need to go here: http://blog.alivate.com.au/poppler-windows/
and install Poppler for Windows (if you're working on Windows machine). At least that solved my problem. Let me know if you're still having it.

**Comment by ohodovaniuk1** [comment]
@apetov Yeah, looks like windows is causing an issue. PDF parser works

**Comment by apetov** [comment]
@ohodovaniuk1 all right, I'm glad that helped!

**Pull request merged**
